heat_template_version: 2016-04-08

description: >
  This Template will install Cinder Docker Volume Plugin (cinderdvp) and configure
  TODO; a lot of parameterization of what is hard coded.

parameters:

resources:
  cinderdvpInstall:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: cinderdvpConfig}
      - config: {get_resource: cinderdvpCommands}

  cinderdvpConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'dict(recurse_array,no_replace)+list(append)'
        write_files:
          - path: "/tmp/cinder-docker.json"
            permissions: "0644"
            owner: "root"
            content: |
              {
                "Endpoint": "http://172.27.31.11:5000/v2.0",
                "Username": "mesos",
                "Password": "solidfire",
                "TenantID": "fa8d19d16d7d42b3814f0184b0fd5f69",
                "DefaultVolSz": 1,
                "HostUUID":
              }

  cinderdvpCommands:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            # setup Cinder-Docker driver.
            UUID=$(uuidgen);sed -i '/HostUUID/ s/$/"'$UUID'"/' /tmp/cinder-docker.json
            mkdir -p /var/lib/cinder/dockerdriver/
            mv /tmp/cinder-docker.json /var/lib/cinder/dockerdriver/config.json
            #curl -sSl https://raw.githubusercontent.com/j-griffith/cinder-docker-driver/master/install.sh | sh
            curl -sSl https://raw.githubusercontent.com/ebalduf/cinder-docker-driver/update_install/install.sh | sh
            systemctl start cinder-docker-driver
          params:
            dummy-param: dummy

outputs:
  OS::stack_id:
    value: {get_resource: cinderdvpInstall}
