resource_registry:
  LIB::Dcos::Users: ./users.yaml
  LIB::Dcos::Keypair: ./keypair.yaml
  LIB::Dcos::SoftwareInstall: ./software-install.yaml
  LIB::Dcos::RebootNotify: ./reboot-notify.yaml
  LIB::Dcos::NdvpInstall: ./ndvp-init.yaml
  LIB::Dcos::SfdvpInstall: ./sfdvp-init.yaml
  LIB::Dcos::CinderdvpInstall: ./cinderdvp-init.yaml

parameter_defaults:
  default_username: dcos
  # Put your key in here. You will be able to use the above account to login
  # This template will generate a key for the root and default user to allow necessary 
  # ssh'ing around to configure the cluster.  You will never see/use that key.
  extra_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDO7RGguqYOGwSN13r91URgkn04aY1rjrT7kae7s6IdCZA920dfch4Wr6mVDNNxt34T4leEhgFOcgYp649qqGPhFshIhv+CJ7YfcD8KqIxh+/WO97quwin668QsB80Tt1pSdqbIGFb8eYr5hNzFKwealuDIG9A/VSUYTp9U4hzfp6XTECA4LFTgvfw8Q32bLKFGMGmKnEizCAb9/znL/We2xnyIz1IDgviQI/3XQtcS4I0kNTyPzuwGw3GOWACYf5z67BI9kazytUfqu6/i4V1MuMyjRpsq0k4qGH3aJAKyI2LPOAfSVy7duBEwzZVFFb665TvA5yikPORy5XMeFGrnp4FPLWDlfi8Svyl+xGgNRXQdXzUzI9qzJiv+heTjOxLK/73rXDDcBpoMfRPXnvEajtySZ7W6MepSwjj/OHQGwNhynzUKP3YaosPynXn1gDsZNZ4v0fOTQR+darTpgx8mgv4wqTCvm/Z8Z9eo08jbxRckybkx/gNyDuvnUae7oLbqF77wcTHlx2u/C9nFpKe0JrfB+bH+/vwA1jEVAthFhiFx3s+6sRxL/6IBcUs37XJ93AXTEfmKA9P4GH1HE4ckxCJvEsglRHYsMScuwuRyiQuodg8HahIR7sjYeosXj/n8tnqjF6B0NCKueSrZvAfeEAY9/u2yTDdYJMgsFMWboQ== ebalduf@applelaptop.balduf.localdomain"
  num_masters: 1
  num_agents: 2
  bootstrap_flavor: mesos.bootstrap
  master_flavor: mesos.master
  agent_flavor: mesos.agent
  image: centos7-software-config
  network: admin_net
  bootstrap_root_size: 60
  master_root_size: 120
  agent_root_size: 60
  public_network: public
  root_type: solidfire
  # these are for sfdvp
  sf_endpoint: "https://admin:solidfire@172.27.1.50/json-rpc/7.0"
  sf_svip: "172.27.25.50:3260"
  sf_account: "mesos"
  # this is for ndvp
  ndvp_endpoint: "https://admin:solidfire@172.27.1.50/json-rpc/7.0"
  ndvp_svip: "172.27.25.50:3260"
  ndvp_account: "MesosCluster"
  # this is for Cinder-docker-driver
  cinder_endpoint: "http://172.27.31.11:5000/v2.0"
  cinder_username: "mesos"
  cinder_password: "solidfire"
  cinder_tenantID: "fa8d19d16d7d42b3814f0184b0fd5f69"
