resource_registry:
  OS::TripleO::Users: ./users.yaml
  OS::TripleO::SoftwareInstall: ./software-install.yaml
  OS::TripleO::NdvpInstall: ./ndvp-init.yaml
  OS::TripleO::SfdvpInstall: ./sfdvp-init.yaml
  OS::TripleO::CinderdvpInstall: ./cinderdvp-init.yaml

parameters:
  flavor: mesos.bootstrap
  image: centos7-software-config
  ssh_key: balduf-hlaptop
  network: admin_net
  root_size: 40

