heat_template_version: 2016-04-08

description: >
  Heat Template to create a Mesos DC/OS cluster

parameters:
  num_masters:
    type: number
    description: The number of Master nodes to create. Default is 1.
  num_agents:
    type: number
    description: The number of Agent nodes to create. Default is 2.
  bootstrap_flavor:
    type: string
    description: The flavor to use to boot the VM
  master_flavor:
    type: string
    description: The flavor to use to boot the VM
  agent_flavor:
    type: string
    description: The flavor to use to boot the VM
  image:
    type: string
    description: The image to use, defaults to CentOS
  network:
    type: string
  bootstrap_root_size:
    type: number
  master_root_size:
    type: number
  agent_root_size:
    type: number
  default_username:
    type: string
    default: dcos

resources:
  key_pair:
    type: LIB::Dcos::Keypair
    properties:
      prefix: { get_param: default_username }

  insert_ssh_key:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: private_key
      config: |
        #!/usr/bin/bash
        echo $private_key > /root/.ssh/id_rsa.raw 
        echo '-----BEGIN RSA PRIVATE KEY-----' > /root/.ssh/id_rsa
        sed 's/ /\n/g' /root/.ssh/id_rsa.raw | sed -n 5,29p >> /root/.ssh/id_rsa
        echo '-----END RSA PRIVATE KEY-----' >> /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa /root/.ssh/id_rsa.raw

  deploy_insert_ssh:
    type: OS::Heat::SoftwareDeployment
    depends_on: DCOS_bootstrap_group
    properties:
      config:
        get_resource: insert_ssh_key
      server:
        { get_attr: [ DCOS_bootstrap_group, resource.0.server ] }
      input_values:
        private_key: { get_attr: [ key_pair, private_key ] }

  install_dcos:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: user
      - name: masters
      - name: agents
      - name: cluster_name
      config: |
        #!/usr/bin/bash
        mkdir -p /root/genconf
        cp /usr/local/bin/ip-detect.sh /root/genconf/ip-detect
        cp /root/.ssh/id_rsa /root/genconf/ssh_key
        cat << EOF > /root/genconf/config.yaml
        ---
        exhibitor_storage_backend: static
        ip_detect_path: genconf/ip-detect
        master_discovery: static
        master_list: $masters
        bootstrap_url: file:///opt/dcos_install_tmp
        cluster_name: $cluster_name
        process_timeout: 10000
        #public_agent_list: $agents
        agent_list: $agents
        resolvers:
        - 172.27.1.251
        - 8.8.8.8
        - 8.8.4.4
        ssh_key_path: genconf/ssh_key
        ssh_port: 22
        ssh_user: $user
        telemetry_enabled: false
        EOF
        cd /root
        # remove the unicode designator
        sed -i 's#u'\''#'\''#g' genconf/config.yaml
        curl -O https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh
        bash dcos_generate_config.sh --genconf
        bash dcos_generate_config.sh --install-prereqs
        bash dcos_generate_config.sh --preflight
        bash dcos_generate_config.sh --deploy
        bash dcos_generate_config.sh --postflight

  deploy_dcos:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_insert_ssh
    depends_on: DCOS_master_group
    depends_on: DCOS_agent_group
    properties:
      config:
        get_resource: install_dcos
      server:
        { get_attr: [ DCOS_bootstrap_group, resource.0.server ] }
      input_values:
        user: { get_param: default_username }
        masters: { get_attr: [ DCOS_master_group, public_ip ] }
        agents: { get_attr: [ DCOS_agent_group, public_ip ] }
        cluster_name: { get_param: 'OS::stack_name' }

  # I run this from the bootstrap node because the list resturned from a Heat
  # resource group needs ugly massaging to get it into the format for a 
  # SoftwareDeploymentGroup.  This is fixed in Newton, but this is to run on 
  # Mitaka for now.
  fix_mesos_hostname:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: theagents
      - name: themasters
      - name: user
      config: |
        #!/usr/bin/bash
        cat << EOF > /tmp/agents.list
          $theagents
        EOF
        cat << EOF > /tmp/masters.list
          $themasters
        EOF
        for ag in `sed 's|\[||g;s|]||g;s|u'\''||g;s|'\''||g;s| ||g;s|,|\n|g' /tmp/masters.list`; do
          echo "Fixing Mesos Hostname: " $ag
          ssh -o StrictHostKeyChecking=no $user@$ag 'PUBIP=$(curl -fsSL http://169.254.169.254/latest/meta-data/public-ipv4); \
                                                     echo "MESOS_HOSTNAME=$PUBIP" | sudo tee -a /opt/mesosphere/etc/mesos-master; \
                                                     sudo reboot'
          sleep 30
        done
        for ag in `sed 's|\[||g;s|]||g;s|u'\''||g;s|'\''||g;s| ||g;s|,|\n|g' /tmp/agents.list`; do
          echo "Fixing Mesos Hostname: " $ag
          ssh -o StrictHostKeyChecking=no $user@$ag 'PUBIP=$(curl -fsSL http://169.254.169.254/latest/meta-data/public-ipv4); \
                                                     echo "MESOS_HOSTNAME=$PUBIP" | sudo tee -a /opt/mesosphere/etc/mesos-slave-common; \
                                                     sudo reboot'
          sleep 30
        done

  deploy_fix_hostname:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_dcos
    properties:
      config:
        get_resource: fix_mesos_hostname
      server:
        { get_attr: [ DCOS_bootstrap_group, resource.0.server ] }
      input_values:
        user: { get_param: default_username }
        theagents: { get_attr: [ DCOS_agent_group, private_ip ] }
        themasters: { get_attr: [ DCOS_master_group, private_ip ] }

  mesos_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          params:
            __prefix__: "mesos_sg"
            __id__: { get_param: "OS::stack_name" }
          template: __prefix__-__id__
      description: Ports for Mesos
      rules:
      - protocol: tcp
        port_range_min: 1
        port_range_max: 65535
      - protocol: udp
        port_range_min: 1
        port_range_max: 65535
# I can't get this to work
#      - remote_mode: "remote_group_id"
#      - protocol: icmp
#      - protocol: tcp
#        port_range_min: 22
#        port_range_max: 22
#      - protocol: tcp
#        port_range_min: 80
#        port_range_max: 80
#      - protocol: tcp
#        port_range_min: 443
#        port_range_max: 443
#      - protocol: tcp
#        port_range_min: 2181
#        port_range_max: 2181
#      - protocol: tcp
#        port_range_min: 5050
#        port_range_max: 5051
#      - protocol: tcp
#        port_range_min: 8080
#        port_range_max: 8080
#      - protocol: tcp
#        port_range_min: 8181
#        port_range_max: 8181

  DCOS_bootstrap_group:
    type: OS::Heat::ResourceGroup
    depends_on: mesos_sg
    properties:
      count: 1
      resource_def:
          type: mesos-node.yaml
          properties:
            flavor: { get_param: bootstrap_flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "mesos_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: bootstrap_root_size }

  DCOS_master_group:
    type: OS::Heat::ResourceGroup
    depends_on: mesos_sg
    properties:
      count: { get_param: num_masters }
      resource_def:
          type: mesos-node.yaml
          properties:
            flavor: { get_param: master_flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups:
            - "default"
            - str_replace:
                 params:
                   __prefix__: "mesos_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: master_root_size }

  DCOS_agent_group:
    type: OS::Heat::ResourceGroup
    depends_on: mesos_sg
    properties:
      count: { get_param: num_agents }
      resource_def:
          type: mesos-node.yaml
          properties:
            flavor: { get_param: agent_flavor }
            image: { get_param: image }
            ssh_key: { get_attr: [ key_pair, name ] }
            sec_groups: 
            - "default"
            - str_replace:
                 params:
                   __prefix__: "mesos_sg"           
                   __id__: { get_param: "OS::stack_name" }
                 template: __prefix__-__id__
            network: { get_param: network }
            root_size: { get_param: agent_root_size }

outputs:
 bootstrap_ip:
    value: { get_attr: [ DCOS_bootstrap_group, public_ip] }
 master_ip:
    value: { get_attr: [ DCOS_master_group, public_ip] }
 agent_ips:
    value: { get_attr: [ DCOS_agent_group, public_ip] }
 public_key:
    value: { get_attr: [ key_pair, public_key ] }
